### ISSUE TITLE
How to change additional config variables?

### ISSUE THREAD

**Issue by janstieler** [bjo3rnf/kirby-plugin-captcha#1]
Hi,
could you explain me how I have to set the additional config variables?
As example if i want to change the captcha width. Where have I write the width value?

Cheers,
Jan

**Comment by bjo3rnf** [comment]
Hi,

simply add `c::set('captcha.width', '250')` to config.php of your site.

Cheers
Björn

**Comment by janstieler** [comment]
Hello Björn,

thanks for your fast reply and your help!
