### ISSUE TITLE
Multiple use on site?

### ISSUE THREAD

**Issue by janstieler** [bjo3rnf/kirby-plugin-captcha#2]
Hi,
is it possible to use it multiple on one site?

Cheers

**Comment by bjo3rnf** [comment]
Hi,
should be possible, yes, using unique DOM ids for each captcha and separate namespaces like so (untested):

```
<img id="captcha1" src="<?php echo url('captcha?namespace=captcha1') ?>" alt="CAPTCHA Image">
<img id="captcha2" src="<?php echo url('captcha?namespace=captcha2') ?>" alt="CAPTCHA Image">
```

Cheers
Björn

**Comment by janstieler** [comment]
Hi,
thanks for your reply.
Using the namespace works for getting different captchaimages. 
But I have an problem to pass the captcha validation. How connect the validation to the namespace?
Actually i don't see anything how the plugin can recognize which captcha it has to validate.

```
<img id="captchaone" src="<?php echo url('captcha?namespace=captchaone') ?>" alt="CAPTCHA Image" class="img-responsive">
<input type="text" class="col-xs-12 col-sm-16 col-md-16 col-lg-20 pull-right" id="contactcaptcha" name="contactcaptcha" maxlength="6" placeholder="<?php echo l::get('captcha') ?>">
<button class="newCaptcha btn btn-default col-xs-11 col-sm-11 col-md-11 col-lg-7 pull-left text-right clearfix" onclick="document.getElementById('captchaone').src = '<?php echo url('captcha?namespace=captchaone') ?>?' + Math.random(); return false"><?php echo l::get('captchaimage') ?></button>
```

```
if(get('contactsubmit')) {
    $contactdata = array(
       …
       'contactcaptcha' => get('contactcaptcha'),
    );
    $contactrules = array(
         …
        'contactcaptcha' => array('required', 'captcha'),
    );
    $contactmessages = array(
        …
        'contactcaptcha' => l::get('captchaerror_contact'),
    );
}
```

Cheers,
Jan

**Comment by bjo3rnf** [comment]
Hi,

well, of course you'll have to register another validator as well. Please see my example code where I assign a validator 'captcha' to the field 'captcha'. Simply add another one with the field name of the additional captcha. Should do the trick. If in doubt please post a gist of your full code.

Cheers
Björn

**Comment by bjo3rnf** [comment]
Hi,

I stand corrected: multiple captchas on a page are not possible _right now_, sorry. I first have to find a way to set the current namespace in the validator - if there is one. I'll keep you updated.

Cheers
Björn

**Comment by bjo3rnf** [comment]
Hi,

I just pushed an updated version that enables namespaces as required. Please try it and feedback is very welcome, thanks.

Cheers
Björn

**Comment by bjo3rnf** [comment]
I'll take the liberty of closing this issue due to the lack of feedback. Feel free to reopen.
